In [4]:
# 1D array
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.itemsize)

[1 2 3 4]
int32
(4,)
4


In [3]:
# 2D array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.dtype)
print(arr2.shape)
print(arr2.itemsize)




[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)
4


In [14]:
# Ways of creating 1D numpy arrays
# 1. Using array()
ar1=np.array([1,2,3,4,5])


# 2 Using fromiter
adic={1:'A',2:'B',3:'C',4:'D'}
alist=[1,2,3,4]
astr="TanuPriyaPathak"
ar2=np.fromiter(adic,dtype=np.int32)
print(ar2)
ar3=np.fromiter(alist,dtype=np.int32)
print(ar3)
ar4=np.fromiter(astr,dtype="U2")
print(ar4)
ar5=np.fromiter(astr,dtype="U2",count=4)
print(ar5)


# 3 Using arange
ar6=np.arange(1,15,2,dtype=np.float32)
print(ar6)


# 4 Using linspace(start,stop,no.of elements in between)=>equally spaced elements
ar7=np.linspace(2.5,8,6)
print(ar7)

[1 2 3 4]
[1 2 3 4]
['T' 'a' 'n' 'u' 'P' 'r' 'i' 'y' 'a' 'P' 'a' 't' 'h' 'a' 'k']
['T' 'a' 'n' 'u']
[ 1.  3.  5.  7.  9. 11. 13.]
[2.5 3.6 4.7 5.8 6.9 8. ]


In [15]:
# Ways of creating 2D np arrays
# 1. Using array()
a1=np.array([[1,2,3,4],[5,6,7,8]])
print(a1)


# 2. Using arange() =>use of reshape()
a2=np.arange(10)
print(a2)
a21=a2.reshape(5,2)
print(a21)



[[1 2 3 4]
 [5 6 7 8]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
# Alternative array creation methods
# 1.Empty arrays
A=np.empty([3,4],dtype=np.int32,order='F')#will store garbage values,'ORDER STORES VALUES IN MEMORY C=ROW WISE F=COLUMN WISE'
print(A)

# 2. Arrays filled with zeros
A0=np.zeros([3,2],dtype=np.int32,order='C')
print(A0)

# 3. Arrays filled with ones
A1=np.ones([4,3],dtype=np.int32,order='C')
print(A1)

# 4.Identity matrix
A2=np.eye(5)
print(A2)

# 5.all values as 1 number
A3=np.full((2,3),6)
print(A3)

# 6. Random value arrays
A31=np.random.rand(3,4)# random floats from 0-1
print(A31)

A32=np.random.rand(3,4)*100 # random floats from 0-100
print(A31)

A33=np.random.randint(5,size=(3,4))# random int from 0-4
print(A33)



[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0]
 [0 0]
 [0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[6 6 6]
 [6 6 6]]
[[0.12892002 0.41759884 0.88480655 0.18405978]
 [0.40118987 0.35070389 0.77541226 0.69563015]
 [0.47346076 0.6685291  0.54040355 0.52081627]]
[[0.12892002 0.41759884 0.88480655 0.18405978]
 [0.40118987 0.35070389 0.77541226 0.69563015]
 [0.47346076 0.6685291  0.54040355 0.52081627]]
[[1 4 2 4]
 [0 4 1 4]
 [4 4 4 3]]
