In [2]:
import numpy as np


In [18]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr2=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13],[13,14,15,16],[10,20,30,40]])
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]
 [13 14 15 16]
 [10 20 30 40]]


In [9]:
# array slices
print(arr1[2::2])
print(arr2[::2,::2])#alternate rows and columns

print(arr2[:,2])#all rows and second column


[ 3  5  7  9 11 13 15]
[[ 1  3]
 [ 7  9]
 [13 15]]
[ 3  6  9 12 15]


In [14]:
#concatenate arrays =>only same dimension arrays can be concatenated 
#axis=0 =>rows
#axis=1=>column

arr3=np.array([[16,17,18,19],[19,20,21,22]])
c1=np.concatenate((arr2,arr3),axis=0)
print(c1)

#flattened array=>converted to 1D array
c2=np.concatenate((arr2,arr3),axis=None)
print(c2)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]
 [13 14 15 16]
 [16 17 18 19]
 [19 20 21 22]]
[ 1  2  3  4  4  5  6  7  7  8  9 10 10 11 12 13 13 14 15 16 16 17 18 19
 19 20 21 22]


In [22]:
# subsets of array- hsplit, vsplit, split
print("hsplit")
h1=np.hsplit(arr2,2)
print(h1)
print("vsplit")

v1,v2=np.vsplit(arr2,2)
print("v1=",v1)
print("v2=",v2)

hsplit
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [10, 20]]), array([[ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [30, 40]])]
vsplit
v1= [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
v2= [[10 11 12 13]
 [13 14 15 16]
 [10 20 30 40]]


In [27]:
# Extracting condition based Non-contiguous subsets
# np.extract(<condition>,<array>)
con1=np.mod(arr2,5)==0
print(con1)
print(" ")
print("Extracted array:")
e1=np.extract(con1,arr2)
print(e1)

[[False False False False]
 [False  True False False]
 [False False False  True]
 [ True False False False]
 [False False  True False]
 [ True  True  True  True]]
 
Extracted array:
[ 5 10 10 15 10 20 30 40]
